version: "3.10"
services:
   worker:
    build: .
    environment:
      API_ID: $API_ID
      API_HASH: $API_HASH
      BOT_TOKEN: $BOT_TOKEN
      ADMINS: $ADMINS
      UPDATE_CHANNEL: $UPDATE_CHANNEL
      DATABASE_NAME: $DATABASE_NAME
      DATABASE_URI: $DATABASE_URI
